### ISSUE TITLE
param to specify root path for temp files

### ISSUE THREAD

**Issue by Kikobeats** [ArtskydJ/create-temp-file#6]
something like:

var createTempFile = require('create-temp-file')({ path: '/my/custom/path' })

in other case uses os temp path.

what's do you think?

**Comment by ArtskydJ** [comment]
If you publish your [tempfile fork](https://github.com/Kikobeats/tempfile) to npm, I would be happy to use it instead.

**Comment by Kikobeats** [comment]
I'm waiting a dependency PR and automatically will be result

**Comment by ArtskydJ** [comment]
Ah, yes, sorry; I didn't notice that...

**Comment by Kikobeats** [comment]
check #7 :-)
